services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AI-Safety_postgres_db_V2
    environment:
      POSTGRES_USER: AI-Safety-Through-Debate
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: AI-Safety-Through-Debate
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - AI-Safety

volumes:
  pg_data:
    driver: local

networks:
  AI-Safety:
    driver: bridge
